---
services:

  postgres_dev:
    container_name: 'postgres-dev'
    image: 'postgres:14.7-alpine'
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    volumes:
      - postgres_data:/data/postgres
    restart: unless-stopped

  mailcatcher:
    container_name: mailcatcher
    image: sj26/mailcatcher
    expose:
      - '${EMAIL_SMTP_PORT}'
      - '${EMAIL_HTTP_PORT}'
    ports:
      - '${EMAIL_SMTP_PORT}:1025'
      - '${EMAIL_HTTP_PORT}:1080'

  tabnews:
    build: .
    container_name: tabnews
    ports:
      - ${WEB_PORT}:3000
    restart: unless-stopped

volumes:
  postgres_data:
