name: HoruSec

on:
  push:
    branches: ["actions-tcc-usp"]

permissions:
  issues: write
  contents: write
  pull-requests: write

jobs:
  checking_code:
    runs-on: ubuntu-latest
    name: SAST Horusec Scan
    steps:
      - uses: actions/checkout@v3

      - name: Run Horusec
        id: run_horusec
        uses: fike/horusec-action@v0.2.2
        with:
          arguments: -c=horusec-config.json -p ./
