name: Dependency-Check

on:
  push:
    branches: ["actions-tcc-usp"]

permissions:
  issues: write
  contents: write
  pull-requests: write

jobs:

  dependency_check:
    name: SAST - Dependency-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run build --if-present

      - name: Check dependency
        uses: dependency-check/Dependency-Check_Action@main
        id: Dependency-Check
        with:
          project: "tabnews"
          path: "."
          format: "HTML"
          out: "reports"
          args: >
            --scan "**/*.js"
            --scan "package.json"
            --failOnCVSS 7
            --enableRetired

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: Dependency-Check report
          path: ${{github.workspace}}/reports
